<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>lpegrex</string>
   </array>
  <key>name</key>
  <string>lpegrex</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.lpegrex</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#ops</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#predef</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#predeffn</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#predefrule</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#capture</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(--.*)</string>
          <key>name</key>
          <string>comment.lpegrex</string>
        </dict>
       </array>
    </dict>
    <key>capture</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\{\})</string>
          <key>name</key>
          <string>storage.type.lpegrex</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{\|)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.lpegrex</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#capture__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\|\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.lpegrex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{~)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.lpegrex</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#capture__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(~\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.lpegrex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{:[A-Za-z_-][A-Za-z0-9_-]*:)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.lpegrex</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#capture__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(:\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.lpegrex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{:)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.lpegrex</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#capture__4</string>
            </dict>
           </array>
          <key>end</key>
          <string>(:\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.lpegrex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.lpegrex</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#capture__5</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.lpegrex</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>capture__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>capture__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>capture__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>capture__4</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>capture__5</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>ops</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(&lt;--|&lt;-\||&lt;==|&lt;-)</string>
          <key>name</key>
          <string>keyword.operator.lpegrex</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(-&gt;|=&gt;|~&gt;|&gt;&gt;|~\?)</string>
          <key>name</key>
          <string>keyword.operator.lpegrex</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.lpegrex</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#ops__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.lpegrex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(=[A-Za-z_-][A-Za-z0-9_-]*\b)</string>
          <key>name</key>
          <string>storage.type.lpegrex</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\$\&apos;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>support.macro.lpegrex</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>support.macro.lpegrex</string>
          <key>end</key>
          <string>(\&apos;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>support.macro.lpegrex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\$\{\})</string>
          <key>name</key>
          <string>support.macro.lpegrex</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\$(?:[A-Za-z][A-Za-z0-9]+|[0-9]+))</string>
          <key>name</key>
          <string>support.macro.lpegrex</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(@)</string>
          <key>name</key>
          <string>support.macro.lpegrex</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([\x{0026}\x{0021}\/\x{003f}\x{005e}\x{002a}\x{002b}\x{0024}.])</string>
          <key>name</key>
          <string>keyword.operator.lpegrex</string>
        </dict>
       </array>
    </dict>
    <key>ops__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>ops__2</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>predef</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(%[A-Za-z_-][A-Za-z0-9_-]*\b)</string>
          <key>name</key>
          <string>constant.language.lpegrex</string>
        </dict>
       </array>
    </dict>
    <key>predeffn</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b(?:tonil|totrue|tofalse|toemptytable|tonumber|tochar|toutf8char|foldleft|foldright|rfoldleft|rfoldright)\b)</string>
          <key>name</key>
          <string>support.function.lpegrex</string>
        </dict>
       </array>
    </dict>
    <key>predefrule</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b(?:KEYWORD|TOKEN|NAME_SUFFIX|SKIP)\b)</string>
          <key>name</key>
          <string>variable.language.lpegrex</string>
        </dict>
       </array>
    </dict>
    <key>string</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\[(?:]|\^]|\^)?)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.lpegrex</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.lpegrex</string>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.lpegrex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.lpegrex</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.lpegrex</string>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.lpegrex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&apos;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.lpegrex</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.lpegrex</string>
          <key>end</key>
          <string>(\&apos;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.lpegrex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\`)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.lpegrex</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.lpegrex</string>
          <key>end</key>
          <string>(\`)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.lpegrex</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>string__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>string__2</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>string__3</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>string__4</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
  </dict>
</dict>
</plist>
